### ISSUE TITLE
Sword is flipped while blocking.

### ISSUE THREAD

**Issue by pleasegivesource** [nekkan/old-animations#2]
![My Video7](https://user-images.githubusercontent.com/66528725/102696083-94cee980-41e0-11eb-9d63-77ceb34859b8.gif)
I do understand why this happened as you use a symmetrical sword on your texture pack, but with an unsymmetrical pack, it is more noticeable.

**Comment by nekkan** [comment]
Does the same problem occur when the "block with shield option" is enabled?

**Comment by pleasegivesource** [comment]
yes

**Comment by nekkan** [comment]
I don't have much time today, so I'll have to fix it tomorrow.

**Comment by nekkan** [comment]
Fixed in latest version. https://github.com/nekkan/old-animations/commit/9f516ff57da8571404657ed3bf134278f249c1d1
